export const fonts = [
  { label: "Roboto", value: "Roboto", category: "sans-serif" },
  { label: "Open Sans", value: "Open Sans", category: "sans-serif" },
  { label: "Merriweather", value: "Merriweather", category: "serif" },
  { label: "Lato", value: "Lato", category: "sans-serif" },
  { label: "Montserrat", value: "Montserrat", category: "sans-serif" },
  { label: "Nunito", value: "Nunito", category: "sans-serif" },
  { label: "Playfair Display", value: "Playfair Display", category: "serif" },
  { label: "Ubuntu", value: "Ubuntu", category: "sans-serif" },
  { label: "PT Serif", value: "PT Serif", category: "serif" },
  { label: "PT Sans", value: "PT Sans", category: "sans-serif" },
  { label: "Inter", value: "Inter", category: "sans-serif" },
  { label: "Fira Sans", value: "Fira Sans", category: "sans-serif" },
  {
    label: "Source Sans Pro",
    value: "Source Sans Pro",
    category: "sans-serif",
  },
  { label: "Rubik", value: "Rubik", category: "sans-serif" },
  { label: "Raleway", value: "Raleway", category: "sans-serif" },
  { label: "Cormorant", value: "Cormorant", category: "serif" },
  { label: "Zilla Slab", value: "Zilla Slab", category: "serif" },
  { label: "Asap", value: "Asap", category: "sans-serif" },
  { label: "IBM Plex Sans", value: "IBM Plex Sans", category: "sans-serif" },
  { label: "IBM Plex Serif", value: "IBM Plex Serif", category: "serif" },
  { label: "IBM Plex Mono", value: "IBM Plex Mono", category: "monospace" },
  { label: "Quicksand", value: "Quicksand", category: "sans-serif" },
  { label: "Roboto Slab", value: "Roboto Slab", category: "serif" },
  { label: "Cairo", value: "Cairo", category: "sans-serif" },
  { label: "Manrope", value: "Manrope", category: "sans-serif" },
  //
  { label: "Poppins", value: "Poppins", category: "sans-serif" },
  { label: "DM Sans", value: "DM Sans", category: "sans-serif" },
  { label: "Space Grotesk", value: "Space Grotesk", category: "sans-serif" },
  { label: "Work Sans", value: "Work Sans", category: "sans-serif" },
  { label: "Libre Franklin", value: "Libre Franklin", category: "sans-serif" },
  { label: "Syne", value: "Syne", category: "sans-serif" },
  { label: "Inconsolata", value: "Inconsolata", category: "monospace" },
  { label: "Proza Libre", value: "Proza Libre", category: "sans-serif" },
  { label: "Spectral", value: "Spectral", category: "serif" },
  { label: "Fraunces", value: "Fraunces", category: "serif" },
  { label: "BioRhyme", value: "BioRhyme", category: "serif" },
  { label: "Alegreya", value: "Alegreya", category: "serif" },
  { label: "Alegreya Sans", value: "Alegreya Sans", category: "sans-serif" },
  { label: "Cardo", value: "Cardo", category: "serif" },
  { label: "Chivo", value: "Chivo", category: "sans-serif" },
  { label: "Neuton", value: "Neuton", category: "serif" },
  { label: "Lora", value: "Lora", category: "serif" },
  { label: "Libre Baskerville", value: "Libre Baskerville", category: "serif" },
  { label: "Eczar", value: "Eczar", category: "serif" },
  { label: "Space Mono", value: "Space Mono", category: "monospace" },
  { label: "DM Serif Text", value: "DM Serif Text", category: "serif" },
  { label: "DM Serif Display", value: "DM Serif Display", category: "serif" },
  {
    label: "Plus Jakarta Sans",
    value: "Plus Jakarta Sans",
    category: "sans-serif",
  },
  { label: "Satoshi", value: "Satoshi", category: "sans-serif" },
  { label: "Aeonik", value: "Aeonik", category: "sans-serif" },
  { label: "Urbanist", value: "Urbanist", category: "sans-serif" },
  { label: "Sora", value: "Sora", category: "sans-serif" },
  { label: "Cal Sans", value: "Cal Sans", category: "sans-serif" },
  {
    label: "Cabinet Grotesk",
    value: "Cabinet Grotesk",
    category: "sans-serif",
  },
  { label: "Geist", value: "Geist", category: "sans-serif" },
  {
    label: "Instrument Sans",
    value: "Instrument Sans",
    category: "sans-serif",
  },
  { label: "Switzer", value: "Switzer", category: "sans-serif" },
  { label: "Eudoxus Sans", value: "Eudoxus Sans", category: "sans-serif" },
  { label: "PP Mori", value: "PP Mori", category: "sans-serif" },
  { label: "Outfit", value: "Outfit", category: "sans-serif" },
  { label: "Archivo Narrow", value: "Archivo Narrow", category: "sans-serif" },
  { label: "Josefin Sans", value: "Josefin Sans", category: "sans-serif" },
  { label: "Josefin Slab", value: "Josefin Slab", category: "serif" },
  { label: "Fjalla One", value: "Fjalla One", category: "sans-serif" },
  { label: "Old Standard TT", value: "Old Standard TT", category: "serif" },
  { label: "Bitter", value: "Bitter", category: "serif" },
  { label: "Varela Round", value: "Varela Round", category: "sans-serif" },
  { label: "Rajdhani", value: "Rajdhani", category: "sans-serif" },
  { label: "Bebas Neue", value: "Bebas Neue", category: "sans-serif" },
  { label: "Anton", value: "Anton", category: "sans-serif" },
  { label: "Cinzel", value: "Cinzel", category: "serif" },
  { label: "Pacifico", value: "Pacifico", category: "handwriting" },
  { label: "Dancing Script", value: "Dancing Script", category: "handwriting" },
  { label: "Indie Flower", value: "Indie Flower", category: "handwriting" },
  { label: "Lobster", value: "Lobster", category: "display" },
  { label: "Monoton", value: "Monoton", category: "display" },
  { label: "Rubik Glitch", value: "Rubik Glitch", category: "display" },
  //
  { label: "Oswald", value: "Oswald", category: "sans-serif" },
  { label: "Barlow", value: "Barlow", category: "sans-serif" },
  { label: "Teko", value: "Teko", category: "sans-serif" },
  { label: "Archivo", value: "Archivo", category: "sans-serif" },
  { label: "Quattrocento", value: "Quattrocento", category: "serif" },
  {
    label: "Quattrocento Sans",
    value: "Quattrocento Sans",
    category: "sans-serif",
  },
  { label: "Fanwood Text", value: "Fanwood Text", category: "serif" },
  { label: "EB Garamond", value: "EB Garamond", category: "serif" },
  { label: "Karla", value: "Karla", category: "sans-serif" },
  { label: "Arimo", value: "Arimo", category: "sans-serif" },
  { label: "Cabin", value: "Cabin", category: "sans-serif" },
  { label: "Lustria", value: "Lustria", category: "serif" },
  { label: "Pinyon Script", value: "Pinyon Script", category: "script" },
  { label: "Caveat", value: "Caveat", category: "handwriting" },
  { label: "Amatic SC", value: "Amatic SC", category: "display" },
  { label: "Gentium Plus", value: "Gentium Plus", category: "serif" },
  { label: "Instrument Serif", value: "Instrument Serif", category: "serif" },
  {
    label: "Special Gothic Expanded One",
    value: "Special Gothic Expanded One",
    category: "display",
  },
  { label: "Liter", value: "Liter", category: "sans-serif" },
  { label: "Playwrite US Trad", value: "Playwrite US Trad", category: "serif" },
  { label: "Playwrite TZ", value: "Playwrite TZ", category: "serif" },
  { label: "Sometype Mono", value: "Sometype Mono", category: "monospace" },
  { label: "Caprasimo", value: "Caprasimo", category: "display" },
  { label: "Albert Sans", value: "Albert Sans", category: "sans-serif" },
  { label: "Modak", value: "Modak", category: "display" },
  { label: "Lexend", value: "Lexend", category: "sans-serif" },
  { label: "Epilogue", value: "Epilogue", category: "sans-serif" },
  { label: "Prata", value: "Prata", category: "serif" },
  { label: "Marcellus", value: "Marcellus", category: "serif" },
  { label: "Outfit", value: "Outfit", category: "sans-serif" },
  { label: "Heebo", value: "Heebo", category: "sans-serif" },
  { label: "SF Pro", value: "SF Pro", category: "sans-serif" },
  { label: "Helvetica", value: "Helvetica", category: "sans-serif" },
  {
    label: "Atkinson Hyperlegible",
    value: "Atkinson Hyperlegible",
    category: "sans-serif",
  },
  {
    label: "Pathway Gothic One",
    value: "Pathway Gothic One",
    category: "sans-serif",
  },
  {
    label: "Barlow Condensed",
    value: "Barlow Condensed",
    category: "sans-serif",
  },
  { label: "Fjalla One", value: "Fjalla One", category: "sans-serif" },
  {
    label: "Roboto Condensed",
    value: "Roboto Condensed",
    category: "sans-serif",
  },
  { label: "Roboto Flex", value: "Roboto Flex", category: "sans-serif" },
  { label: "Noto Sans", value: "Noto Sans", category: "sans-serif" },
  { label: "Source Sans 3", value: "Source Sans 3", category: "sans-serif" },
  { label: "Albert Sans", value: "Albert Sans", category: "sans-serif" },
  { label: "Praxis Grotesk", value: "Praxis Grotesk", category: "sans-serif" },
  { label: "Zodiak", value: "Zodiak", category: "display" },
  { label: "Sentient", value: "Sentient", category: "display" },
  { label: "Gambara", value: "Gambara", category: "serif" },
  { label: "Pencerio", value: "Pencerio", category: "handwriting" },
  { label: "Gotu", value: "Gotu", category: "serif" },
];
