export const fonts = [
  { label: "Roboto", value: "Roboto", category: "sans-serif" },
  { label: "Open Sans", value: "Open Sans", category: "sans-serif" },
  { label: "Merriweather", value: "Merriweather", category: "serif" },
  { label: "Lato", value: "Lato", category: "sans-serif" },
  { label: "Montserrat", value: "Montserrat", category: "sans-serif" },
  { label: "Nunito", value: "Nunito", category: "sans-serif" },
  { label: "Playfair Display", value: "Playfair Display", category: "serif" },
  { label: "Ubuntu", value: "Ubuntu", category: "sans-serif" },
  { label: "PT Serif", value: "PT Serif", category: "serif" },
  { label: "PT Sans", value: "PT Sans", category: "sans-serif" },
  { label: "Inter", value: "Inter", category: "sans-serif" },
  { label: "Fira Sans", value: "Fira Sans", category: "sans-serif" },
  {
    label: "Source Sans Pro",
    value: "Source Sans Pro",
    category: "sans-serif",
  },
  { label: "Rubik", value: "Rubik", category: "sans-serif" },
  { label: "Raleway", value: "Raleway", category: "sans-serif" },
  { label: "Cormorant", value: "Cormorant", category: "serif" },
  { label: "Zilla Slab", value: "Zilla Slab", category: "serif" },
  { label: "Asap", value: "Asap", category: "sans-serif" },
  { label: "IBM Plex Sans", value: "IBM Plex Sans", category: "sans-serif" },
  { label: "IBM Plex Serif", value: "IBM Plex Serif", category: "serif" },
  { label: "IBM Plex Mono", value: "IBM Plex Mono", category: "monospace" },
  { label: "Quicksand", value: "Quicksand", category: "sans-serif" },
  { label: "Roboto Slab", value: "Roboto Slab", category: "serif" },
  { label: "Cairo", value: "Cairo", category: "sans-serif" },
  { label: "Manrope", value: "Manrope", category: "sans-serif" },
  {
    label: "Wix Madefor Display",
    value: "Wix Madefor Display",
    category: "sans-serif",
  },
];
