import { Product } from "../types";

// export const mockProducts: Product[] = [
//   {
//     id: "55001",
//     title: 'Комплект постільної білизни "Тигри"',
//     description:
//       'Постільна білизна "Тигри" 🐯 стиль і сила в кожному дотику. Країна виробник: Україна. Тканина: Бязь GOLD. Щільність: 115 г/м². Колір: чорний з принтом тигрів.',
//     html_description:
//       '<![CDATA[ Постільна білизна "Тигри" 🐯 стиль і сила в кожному дотику<br/>Країна виробник: Україна<br/>Тканина: Бязь GOLD<br/>Щільність: 115 г/м²<br/>Колір: чорний з принтом тигрів ]]>',
//     link: "https://cottonhome.site/komplekt-postilnoi-bilyzny-tyhr/",
//     image_link:
//       "https://my.feededify.app/feedmaker/55001.jpg?v=331B18E73631257115C502DEBCB9561C",
//     additional_image_links: [
//       "https://cottonhome.site/images/55001-1.jpg",
//       "https://cottonhome.site/images/55001-2.jpg",
//     ],
//     availability: "in stock",
//     stock_quantity: 48,
//     price: { value: 798, currency: "UAH" },
//     sale_price: { value: 399, currency: "UAH" },
//     sale_price_effective_date: "2025-08-01/2025-09-15",
//     google_product_category: 4171,
//     item_group_id: "457_17",
//     product_type: "Постільна білизна",
//     brand: "CottonHome",
//     condition: "new",
//     attributes: {
//       material: "Бязь GOLD",
//       density_g_m2: 115,
//       color: "black",
//       size_set: "Полуторний",
//     },
//     variants: [
//       {
//         id: "55001-1",
//         size: "1.5",
//         color: "black",
//         price: 798,
//         availability: "in stock",
//       },
//     ],
//     rating: { avg: 4.6, count: 123 },
//     reviews: [
//       {
//         user: "Олена",
//         text: "Дуже м'яка, рекомендую.",
//         rating: 5,
//         date: "2025-06-21",
//       },
//     ],
//     tags: ["bedding", "cotton", "GOLD"],
//     shipping: {
//       weight_kg: 1.2,
//       dimensions_cm: [40, 30, 6],
//       shipping_class: "standard",
//     },
//     created_at: "2025-01-10T12:34:00Z",
//   },

//   {
//     id: "55002",
//     title: 'Комплект постільної білизни "Тигри" (2-спальний)',
//     description: 'Більш широкий комплект "Тигри" для великого ліжка.',
//     link: "https://cottonhome.site/komplekt-postilnoi-bilyzny-tyhr/819/",
//     image_link:
//       "https://my.feededify.app/feedmaker/55002.jpg?v=9F336947C807A3470FD09052F900DE38",
//     availability: "in stock",
//     stock_quantity: 12,
//     price: { value: 998, currency: "UAH" },
//     sale_price: { value: 499, currency: "UAH" },
//     google_product_category: 4171,
//     item_group_id: "457_17",
//     product_type: "Постільна білизна",
//     brand: "CottonHome",
//     condition: "new",
//     attributes: {
//       material: "Бязь GOLD",
//       color: "black",
//       set_size: "2-спальний",
//     },
//     variants: [
//       {
//         id: "55002-1",
//         size: "2.0",
//         color: "black",
//         price: 998,
//         availability: "in stock",
//       },
//     ],
//     rating: { avg: 4.4, count: 45 },
//     tags: ["bedding", "double"],
//   },

//   {
//     id: "55003",
//     title: 'Комплект постільної білизни "Тигри" (євро)',
//     description: "Євро комплект. Велика кількість різних SKU.",
//     link: "https://cottonhome.site/komplekt-postilnoi-bilyzny-tyhr/820/",
//     image_link: null,
//     availability: "in stock",
//     stock_quantity: 0,
//     price: { value: 1198, currency: "UAH" },
//     sale_price: { value: 599, currency: "UAH" },
//     sale_price_effective_date: "2025-09-01/2025-09-30",
//     google_product_category: 4171,
//     item_group_id: "457_17",
//     product_type: "Постільна білизна",
//     brand: "CottonHome",
//     condition: "new",
//     attributes: { color: "black", package_count: 1 },
//     variants: [],
//     tags: [],
//   },

//   {
//     id: "55005",
//     title: 'Комплект постільної білизни "Зіркове небо"',
//     description: "Затишок під зоряним небом, світло-блакитний відтінок.",
//     link: "https://cottonhome.site/komplekt-postilnoi-bilyzny-zirkove-nebo/",
//     image_link:
//       "https://my.feededify.app/feedmaker/55005.jpg?v=25FDE559B3C5D4D32CD018A53D3EC284",
//     availability: "in stock",
//     stock_quantity: 200,
//     price: { value: 798, currency: "UAH" },
//     sale_price: { value: 399, currency: "UAH" },
//     google_product_category: 4171,
//     item_group_id: "457_18",
//     product_type: "Постільна білизна",
//     brand: "CottonHome",
//     condition: "new",
//     attributes: { pattern: "stars", color: "blue" },
//     variants: [
//       { id: "55005-s", size: "single", price: 798 },
//       { id: "55005-d", size: "double", price: 998 },
//     ],
//     rating: { avg: 4.8, count: 321 },
//   },

//   {
//     id: "55017",
//     title: 'Комплект постільної білизни "Шоколадна насолода"',
//     description: "Коричневий набір, теплий тон.",
//     link: "https://cottonhome.site/komplekt-postilnoi-bilyzny-shokoladna-nasoloda/",
//     image_link:
//       "https://cottonhome.site/content/images/35/komplekt-shokolad.jpg",
//     availability: "out of stock",
//     stock_quantity: 0,
//     price: { value: 798, currency: "UAH" },
//     sale_price: { value: 399, currency: "UAH" },
//     google_product_category: 4171,
//     item_group_id: "457_21",
//     product_type: "Постільна білизна",
//     brand: "CottonHome",
//     condition: "new",
//     attributes: { color: "brown", scent: null },
//     tags: ["seasonal"],
//   },

//   {
//     id: "55019",
//     title: 'Комплект постільної білизни "Шоколадна насолода" (комплект)',
//     link: "https://cottonhome.site/komplekt-postilnoi-bilyzny-shokoladna-nasoloda/836/",
//     image_link:
//       "https://my.feededify.app/feedmaker/55019.jpg?v=67692D4EE52901455C7E1FACC8F8D180",
//     availability: "in stock",
//     stock_quantity: 9,
//     price: { value: 1198, currency: "UAH" },
//     sale_price: { value: 599, currency: "UAH" },
//     google_product_category: 4171,
//     item_group_id: "457_21",
//     product_type: "Постільна білизна",
//     brand: "CottonHome",
//     condition: "new",
//   },

//   {
//     id: "55021",
//     title: 'Комплект постільної білизни "Мармур"',
//     description: "Мармуровий принт, ексклюзивна серія.",
//     link: "https://cottonhome.site/komplekt-postilnoi-bilyzny-marmur/",
//     image_link:
//       "https://my.feededify.app/feedmaker/55021.jpg?v=94CFA7B04752506C45F06B0522497931",
//     additional_image_link:
//       "https://cottonhome.site/content/images/30/komplekt-marmur.png",
//     availability: "in stock",
//     stock_quantity: 5,
//     price: { value: 798, currency: "UAH" },
//     sale_price: { value: 398, currency: "UAH" },
//     google_product_category: 4171,
//     item_group_id: "457_28",
//     product_type: "Постільна білизна",
//     brand: "CottonHome",
//     condition: "new",
//     attributes: { material: "Бязь GOLD", color: "marble" },
//   },

//   {
//     id: "55057",
//     title: 'Комплект постільної білизни "Релакс"',
//     link: "https://cottonhome.site/komplekt-postilnoi-bilyzny-relaks/",
//     image_link: "https://my.feededify.app/feedmaker/55057.jpg?v=2913EF8C",
//     availability: "in stock",
//     stock_quantity: 73,
//     price: { value: 798, currency: "UAH" },
//     sale_price: { value: 399, currency: "UAH" },
//     item_group_id: "457_31",
//     brand: "CottonHome",
//     condition: "new",
//   },

//   {
//     id: "55065",
//     title: 'Комплект постільної білизни "Білий"',
//     link: "https://cottonhome.site/komplekt-postilnoi-bilyzny-bilyi/",
//     image_link: "https://my.feededify.app/feedmaker/55065.jpg?v=A6F75FD0",
//     availability: "in stock",
//     stock_quantity: 120,
//     price: { value: 798, currency: "UAH" },
//     sale_price: { value: 399, currency: "UAH" },
//     item_group_id: "457_33",
//     brand: "CottonHome",
//     condition: "new",
//   },

//   {
//     id: "55077",
//     title: 'Комплект постільної білизни "Цвіт сакури"',
//     description: "Ніжні кольори, флористичний принт.",
//     link: "https://cottonhome.site/komplekt-postilnoi-bilyzny-tsvit-sakura/933/",
//     image_link: "https://my.feededify.app/feedmaker/55077.jpg?v=638FB5A8",
//     availability: "in stock",
//     stock_quantity: 30,
//     price: { value: 798, currency: "UAH" },
//     sale_price: { value: 399, currency: "UAH" },
//     item_group_id: "457_36",
//     brand: "CottonHome",
//     condition: "new",
//   },

//   {
//     id: "21001",
//     title: "Ремінець Upex Single Tour для Apple Watch Indigo Epsom Leather",
//     description:
//       "Ремінець для Apple Watch (42/41/40/38). Indigo Epsom leather.",
//     link: "https://ivan-chohol.ua/remeshok-21001",
//     image_link: "https://ivan-chohol.ua/image/catalog/product-21001.jpg",
//     additional_image_links: [
//       "https://ivan-chohol.ua/image/catalog/product_image-21001-1.jpg",
//       "https://ivan-chohol.ua/image/catalog/product_image-21001-2.jpg",
//     ],
//     availability: "in stock",
//     stock_quantity: 18,
//     price: { value: 2399, currency: "UAH" },
//     sale_price: { value: 1549, currency: "UAH" },
//     sale_price_effective_date: "2025-09-07/2026-09-07",
//     google_product_category: 2353,
//     item_group_id: "UPEX_SINGLE_42",
//     product_type: "Watch strap",
//     brand: "Upex",
//     condition: "new",
//     attributes: {
//       compatible_with: ["Apple Watch 42", "41", "40", "38"],
//       material: "Epsom Leather",
//       color: "indigo",
//     },
//     variants: [
//       {
//         id: "21001-38",
//         size: 38,
//         price: 2399,
//         availability: "in stock",
//       },
//       {
//         id: "21001-42",
//         size: 42,
//         price: 2399,
//         availability: "in stock",
//       },
//     ],
//     rating: { avg: 4.7, count: 78 },
//   },

//   {
//     id: "21002",
//     title: "Ремінець Upex Single Tour Black Swift Leather",
//     link: "https://ivan-chohol.ua/remeshok-21002",
//     image_link: "https://ivan-chohol.ua/image/catalog/product-21002.jpg",
//     availability: "in stock",
//     stock_quantity: 0,
//     price: { value: 2399, currency: "UAH" },
//     sale_price: { value: 1549, currency: "UAH" },
//     sale_price_effective_date: "2025-09-07/2026-09-07",
//     google_product_category: 2353,
//     item_group_id: "UPEX_SINGLE_42",
//     brand: "Upex",
//     condition: "new",
//   },

//   {
//     id: "21010",
//     title: "Ремінець Upex Double Tour Feu Epsom Leather",
//     link: "https://ivan-chohol.ua/remeshok-21010",
//     image_link: "https://ivan-chohol.ua/image/catalog/product-21010.jpg",
//     availability: "preorder",
//     stock_quantity: 0,
//     price: { value: 2999, currency: "UAH" },
//     sale_price: { value: 1989, currency: "UAH" },
//     sale_price_effective_date: "2025-09-07/2026-09-07",
//     google_product_category: 2353,
//     item_group_id: "UPEX_DOUBLE_42",
//     brand: "Upex",
//     condition: "new",
//     attributes: { type: "Double Tour", origin: "EU" },
//   },

//   {
//     id: "21346",
//     title: "Ремінець Upex Single Tour Feu Epsom (1-3 series)",
//     link: "https://ivan-chohol.ua/remeshok-21346",
//     image_link: "https://ivan-chohol.ua/image/catalog/48401.jpg",
//     availability: "in stock",
//     stock_quantity: 54,
//     price: { value: 2399, currency: "UAH" },
//     sale_price: { value: 1549, currency: "UAH" },
//     sale_price_effective_date: "2025-09-07/2026-09-07",
//     google_product_category: 2353,
//     item_group_id: "UPEX_SINGLE_1_3",
//     brand: "Upex",
//     condition: "new",
//   },

//   {
//     id: "58738",
//     title: "Ремінець Upex Single Tour Brique/Beton Swift Leather",
//     link: "https://ivan-chohol.ua/remeshok-58738",
//     image_link: "https://ivan-chohol.ua/image/catalog/cases/44412.jpg",
//     availability: "in stock",
//     stock_quantity: 7,
//     price: { value: 2399, currency: "UAH" },
//     sale_price: { value: 1549, currency: "UAH" },
//     google_product_category: 2353,
//     item_group_id: "UPEX_SINGLE_42",
//     brand: "Upex",
//     condition: "new",
//   },

//   {
//     id: "99901",
//     title: 'Подушка ортопедична "SleepWell"',
//     description: "Ортопедична подушка з пінополіуретану, регульована висота.",
//     link: "https://example.com/sleepwell/99901",
//     image_link: "https://example.com/images/99901.png",
//     availability: "backorder",
//     stock_quantity: 0,
//     price: { value: 1299, currency: "UAH" },
//     sale_price: null,
//     google_product_category: 5020,
//     item_group_id: "SLEEP_01",
//     product_type: "Подушка",
//     brand: "SleepWell",
//     condition: "new",
//     attributes: {
//       fill: "memory foam",
//       height_cm: [8, 12],
//       washable_cover: true,
//     },
//     shipping: { weight_kg: 1.8, dimensions_cm: [60, 40, 12] },
//   },

//   {
//     id: "40001",
//     title: 'Наматрацник водовідштовхувальний "DryGuard"',
//     link: "https://example.com/dryguard/40001",
//     image_link: "https://example.com/images/40001.jpg",
//     availability: "in stock",
//     stock_quantity: 250,
//     price: { value: 499, currency: "UAH" },
//     sale_price: { value: 399, currency: "UAH" },
//     google_product_category: 4171,
//     item_group_id: "MATTRESS_PROT_01",
//     product_type: "Наматрацник",
//     brand: "HomeProtect",
//     condition: "new",
//     attributes: {
//       sizes: ["90x200", "160x200", "180x200"],
//       waterproof: true,
//     },
//     tags: ["accessory", "waterproof"],
//   },

//   {
//     id: "discont-01",
//     title: "Старий колекційний комплект (discontinued)",
//     description:
//       "Знятий з виробництва комплект, товар зі статусом discontinued.",
//     link: "https://cottonhome.site/discontinued/01",
//     image_link: null,
//     availability: "discontinued",
//     stock_quantity: 0,
//     price: { value: 0, currency: "UAH" },
//     sale_price: null,
//     google_product_category: 4171,
//     item_group_id: "DISCONT_01",
//     brand: "CottonHome",
//     condition: "used",
//   },

//   {
//     id: "multi-currency-1",
//     title: "Тестовий товар (EUR pricing)",
//     link: "https://example.com/multi/1",
//     image_link: "https://example.com/images/multi1.jpg",
//     availability: "in stock",
//     stock_quantity: 6,
//     price: { value: 29.99, currency: "EUR" },
//     sale_price: { value: 24.99, currency: "EUR" },
//     google_product_category: 9999,
//     item_group_id: "MULTI_01",
//     brand: "TestBrand",
//     condition: "new",
//     attributes: { promo: "euro-test" },
//   },

//   {
//     id: "edge-blank-fields",
//     title: "Товар з пропущеними полями",
//     link: null,
//     image_link: null,
//     availability: "in stock",
//     price: null,
//     google_product_category: null,
//     item_group_id: "EDGE_01",
//     brand: null,
//     condition: "new",
//   },

//   {
//     id: "complex-variants-01",
//     title: 'Комплект "Mix & Match" (мультіваріант)',
//     description: "Набір з багатьма варіантами кольору і розміру.",
//     link: "https://example.com/mixmatch/complex-01",
//     image_link: "https://example.com/images/mixmatch.jpg",
//     availability: "in stock",
//     stock_quantity: 300,
//     price: { value: 1599, currency: "UAH" },
//     sale_price: { value: 1299, currency: "UAH" },
//     google_product_category: 4171,
//     item_group_id: "MIX_001",
//     brand: "CustomLine",
//     condition: "new",
//     attributes: {
//       colors: ["red", "green", "navy", "beige"],
//       sizes: ["S", "M", "L", "XL"],
//     },
//     variants: [
//       {
//         id: "c-01-S-red",
//         size: "S",
//         color: "red",
//         price: 1599,
//         stock: 10,
//       },
//       {
//         id: "c-01-M-navy",
//         size: "M",
//         color: "navy",
//         price: 1599,
//         stock: 5,
//       },
//       {
//         id: "c-01-L-beige",
//         size: "L",
//         color: "beige",
//         price: 1599,
//         stock: 0,
//         availability: "out of stock",
//       },
//     ],
//     rating: { avg: 4.2, count: 12 },
//     tags: ["mix", "bundle"],
//   },

//   {
//     id: "gift-001",
//     title: "Подарунковий сертифікат 1000 UAH",
//     description: "Електронний сертифікат на 1000 UAH, негнучкий.",
//     link: "https://shop.example.com/gift/1000",
//     image_link: "https://shop.example.com/images/gift-1000.png",
//     availability: "in stock",
//     stock_quantity: 9999,
//     price: { value: 1000, currency: "UAH" },
//     sale_price: null,
//     google_product_category: 239,
//     item_group_id: "GIFT_CARDS",
//     product_type: "Gift card",
//     brand: "Shop",
//     condition: "new",
//     attributes: { redeemable_online: true },
//   },

//   {
//     id: "bundle-01",
//     title: 'Набір: Подушка + Наматрацник + Комплект "Релакс"',
//     description: "Промо-набір, знижка на комплект.",
//     link: "https://example.com/bundle/01",
//     image_link: "https://example.com/images/bundle-01.jpg",
//     availability: "in stock",
//     stock_quantity: 15,
//     price: { value: 2499, currency: "UAH" },
//     sale_price: { value: 1999, currency: "UAH" },
//     google_product_category: 4171,
//     item_group_id: "BUNDLE_001",
//     brand: "CottonHome",
//     condition: "new",
//     attributes: {
//       contains: ["Подушка 99901", "Наматрацник 40001", "Комплект 55057"],
//     },
//   },
// ];

// src/constants/mockProductsFlat.ts

export const mockProducts: Product[] = [
  {
    id: "55001",
    title: `Комплект постільної білизни Тигри 234234 Комплект постільної білизни Тигри 4123123123123 `,
    description: `Постільна білизна "Тигри" — бязь GOLD, щільність 115 г/м², чорний з принтом тигрів.`,
    link: "https://cottonhome.site/komplekt-postilnoi-bilyzny-tyhr/",
    image_link:
      "https://my.feededify.app/feedmaker/e3ab1a03-c9cc-4a80-80c4-f15f8c42092a/55001.jpg?v=331B18E73631257115C502DEBCB9561C",
    availability: "in stock",
    price: "798 UAH",
    sale_price: "399 UAH",
    google_product_category: "4171",
    item_group_id: "457_17",
    product_type: "Постільна білизна",
    brand: "CottonHome",
    condition: "new",
  },

  {
    id: "55002",
    // title: `Комплект постільної білизни "Тигри"`,
    description: `Аналогічний комплект "Тигри" — бязь GOLD, 115 г/м².`,
    link: "https://cottonhome.site/komplekt-postilnoi-bilyzny-tyhr/819/",
    image_link:
      "https://my.feededify.app/feedmaker/e3ab1a03-c9cc-4a80-80c4-f15f8c42092a/55002.jpg?v=9F336947C807A3470FD09052F900DE38",
    availability: "in stock",
    price: "998 UAH",
    sale_price: "499 UAH",
    google_product_category: "4171",
    item_group_id: "457_17",
    product_type: "Постільна білизна",
    brand: "CottonHome",
    condition: "new",
  },

  {
    id: "55003",
    title: `Комплект постільної білизни "Тигри"`,
    description: `Євро-версія комплекту "Тигри" — бязь GOLD, 115 г/м².`,
    link: "https://cottonhome.site/komplekt-postilnoi-bilyzny-tyhr/820/",
    image_link:
      "https://my.feededify.app/feedmaker/e3ab1a03-c9cc-4a80-80c4-f15f8c42092a/55003.jpg?v=1C7894B302CAD25D3D3317B5C597B90C",
    availability: "in stock",
    price: "1198 UAH",
    sale_price: "599 UAH",
    google_product_category: "4171",
    item_group_id: "457_17",
    product_type: "Постільна білизна",
    brand: "CottonHome",
    condition: "new",
  },

  {
    id: "55004",
    title: `Комплект постільної білизни "Тигри"`,
    description: `Ще один варіант комплекту "Тигри" — бязь GOLD.`,
    link: "https://cottonhome.site/komplekt-postilnoi-bilyzny-tyhr/821/",
    image_link:
      "https://my.feededify.app/feedmaker/e3ab1a03-c9cc-4a80-80c4-f15f8c42092a/55004.jpg?v=30D639E3A62F0958D9D2B0BD1B49CB19",
    availability: "in stock",
    price: "1399 UAH",
    sale_price: "699 UAH",
    google_product_category: "4171",
    item_group_id: "457_17",
    product_type: "Постільна білизна",
    brand: "CottonHome",
    condition: "new",
  },

  {
    id: "55005",
    title: `Комплект постільної білизни "Зіркове небо"`,
    description: `"Зіркове небо" — світло-блакитний, бязь GOLD, 115 г/м².`,
    link: "https://cottonhome.site/komplekt-postilnoi-bilyzny-zirkove-nebo/",
    image_link:
      "https://my.feededify.app/feedmaker/e3ab1a03-c9cc-4a80-80c4-f15f8c42092a/55005.jpg?v=25FDE559B3C5D4D32CD018A53D3EC284",
    availability: "in stock",
    price: "798 UAH",
    sale_price: "399 UAH",
    google_product_category: "4171",
    item_group_id: "457_18",
    product_type: "Постільна білизна",
    brand: "CottonHome",
    condition: "new",
  },

  {
    id: "55006",
    title: `Комплект постільної білизни "Зіркове небо"`,
    description: `Варіант "Зіркове небо" — бязь GOLD.`,
    link: "https://cottonhome.site/komplekt-postilnoi-bilyzny-zirkove-nebo/823/",
    image_link:
      "https://my.feededify.app/feedmaker/e3ab1a03-c9cc-4a80-80c4-f15f8c42092a/55006.jpg?v=E0461F36FAE3DE569B8526EAD4DE2005",
    availability: "in stock",
    price: "998 UAH",
    sale_price: "499 UAH",
    google_product_category: "4171",
    item_group_id: "457_18",
    product_type: "Постільна білизна",
    brand: "CottonHome",
    condition: "new",
  },

  {
    id: "55007",
    title: `Комплект постільної білизни "Зіркове небо"`,
    description: `Ще варіант "Зіркове небо".`,
    link: "https://cottonhome.site/komplekt-postilnoi-bilyzny-zirkove-neb/",
    image_link:
      "https://my.feededify.app/feedmaker/e3ab1a03-c9cc-4a80-80c4-f15f8c42092a/55007.jpg?v=A98E066ECA41A6DCF5EBD8E128F51F03",
    availability: "in stock",
    price: "1198 UAH",
    sale_price: "599 UAH",
    google_product_category: "4171",
    item_group_id: "457_18",
    product_type: "Постільна білизна",
    brand: "CottonHome",
    condition: "new",
  },

  {
    id: "55008",
    title: `Комплект постільної білизни "Зіркове небо"`,
    description: `Варіація комплекта "Зіркове небо".`,
    link: "https://cottonhome.site/komplekt-postilnoi-bilyzny-zirkove-nebo/id/",
    image_link:
      "https://my.feededify.app/feedmaker/e3ab1a03-c9cc-4a80-80c4-f15f8c42092a/55008.jpg?v=A9CC4F2590BCACECA4185CDAD6F7BCB4",
    availability: "in stock",
    price: "1399 UAH",
    sale_price: "699 UAH",
    google_product_category: "4171",
    item_group_id: "457_18",
    product_type: "Постільна білизна",
    brand: "CottonHome",
    condition: "new",
  },

  {
    id: "55017",
    title: `Комплект постільної білизни "Шоколадна насолода"`,
    description: `Шоколадна насолода — коричневий комплект, бязь GOLD, 115 г/м².`,
    link: "https://cottonhome.site/komplekt-postilnoi-bilyzny-shokoladna-nasoloda/",
    image_link:
      "https://cottonhome.site/content/images/35/komplekt-postilnoi-bilyzny-zahadka834-50740350241422_+c8d28607ab.jpg",
    availability: "out of stock",
    price: "798 UAH",
    sale_price: "399 UAH",
    google_product_category: "4171",
    item_group_id: "457_21",
    product_type: "Постільна білизна",
    brand: "CottonHome",
    condition: "new",
  },

  {
    id: "55018",
    title: `Комплект постільної білизни "Шоколадна насолода"`,
    description: `Інший варіант "Шоколадна насолода".`,
    link: "https://cottonhome.site/komplekt-postilnoi-bilyzny-shokoladna-nasoloda/835/",
    image_link:
      "https://cottonhome.site/content/images/36/komplekt-postilnoi-bilyzny-zahadka..-54037282973038_+c2469dbc3e.jpg",
    availability: "out of stock",
    price: "998 UAH",
    sale_price: "499 UAH",
    google_product_category: "4171",
    item_group_id: "457_21",
    product_type: "Постільна білизна",
    brand: "CottonHome",
    condition: "new",
  },

  {
    id: "55019",
    title: `Комплект постільної білизни "Шоколадна насолода"`,
    description: `Комплект "Шоколадна насолода" — інший SKU.`,
    link: "https://cottonhome.site/komplekt-postilnoi-bilyzny-shokoladna-nasoloda/836/",
    image_link:
      "https://my.feededify.app/feedmaker/e3ab1a03-c9cc-4a80-80c4-f15f8c42092a/55019.jpg?v=67692D4EE52901455C7E1FACC8F8D180",
    availability: "in stock",
    price: "1198 UAH",
    sale_price: "599 UAH",
    google_product_category: "4171",
    item_group_id: "457_21",
    product_type: "Постільна білизна",
    brand: "CottonHome",
    condition: "new",
  },

  {
    id: "55020",
    title: `Комплект постільної білизни "Шоколадна насолода"`,
    description: `Ще один SKU "Шоколадна насолода".`,
    link: "https://cottonhome.site/komplekt-postilnoi-bilyzny-shokoladna-nasoloda/837/",
    image_link:
      "https://my.feededify.app/feedmaker/e3ab1a03-c9cc-4a80-80c4-f15f8c42092a/55020.jpg?v=59C1C3F9DC5AC054F80ACECA48445B43",
    availability: "in stock",
    price: "1399 UAH",
    sale_price: "699 UAH",
    google_product_category: "4171",
    item_group_id: "457_21",
    product_type: "Постільна білизна",
    brand: "CottonHome",
    condition: "new",
  },

  {
    id: "55025",
    title: `Комплект постільної білизни "Ромашкове поле"`,
    description: `Ромашкове поле — блакитний квітковий принт, бязь GOLD.`,
    link: "https://cottonhome.site/komplekt-postilnoi-bilyzny-romashkove-pole/842/",
    image_link:
      "https://cottonhome.site/content/images/43/komplekt-postilnoi-bilyzny-romashkove-poleid-81272543225378_+d27e0cab5c.jpg",
    availability: "out of stock",
    price: "798 UAH",
    sale_price: "399 UAH",
    google_product_category: "4171",
    item_group_id: "457_23",
    product_type: "Постільна білизна",
    brand: "CottonHome",
    condition: "new",
  },

  {
    id: "55026",
    title: `Комплект постільної білизни "Ромашкове поле"`,
    description: `Варіант "Ромашкове поле".`,
    link: "https://cottonhome.site/komplekt-postilnoi-bilyzny-romashkove-pole/843/",
    image_link:
      "https://cottonhome.site/content/images/44/-73197102776446_+15ab3c4f97.jpg",
    availability: "out of stock",
    price: "998 UAH",
    sale_price: "499 UAH",
    google_product_category: "4171",
    item_group_id: "457_23",
    product_type: "Постільна білизна",
    brand: "CottonHome",
    condition: "new",
  },

  {
    id: "55027",
    title: `Комплект постільної білизни "Ромашкове поле"`,
    description: `Ще один SKU "Ромашкове поле".`,
    link: "https://cottonhome.site/komplekt-postilnoi-bilyzny-romashkove-pole/844/",
    image_link:
      "https://my.feededify.app/feedmaker/e3ab1a03-c9cc-4a80-80c4-f15f8c42092a/55027.jpg?v=34BE92B9CE5CDEFF5058605A24D6439C",
    availability: "in stock",
    price: "1198 UAH",
    sale_price: "599 UAH",
    google_product_category: "4171",
    item_group_id: "457_23",
    product_type: "Постільна білизна",
    brand: "CottonHome",
    condition: "new",
  },

  {
    id: "55028",
    title: `Комплект постільної білизни "Ромашкове поле"`,
    description: `Варіація "Ромашкове поле".`,
    link: "https://cottonhome.site/komplekt-postilnoi-bilyzny-romashkove-pole/",
    image_link:
      "https://cottonhome.site/content/images/46/komplekt-postilnoi-bilyzny-romashkove-pole-45022326867707_+a1547e867e.jpg",
    availability: "out of stock",
    price: "1399 UAH",
    sale_price: "699 UAH",
    google_product_category: "4171",
    item_group_id: "457_23",
    product_type: "Постільна білизна",
    brand: "CottonHome",
    condition: "new",
  },

  {
    id: "55041",
    title: `Комплект постільної білизни "Париж"`,
    description: `"Париж" — елегантний класичний дизайн, бязь GOLD.`,
    link: "https://cottonhome.site/komplekt-postilnoi-bilyzny-paryzh/858/",
    image_link:
      "https://cottonhome.site/content/images/9/komplekt-postilnoi-bilyzny-paryzhid-99153174449520_+c1dcde4ccc.jpg",
    availability: "out of stock",
    price: "798 UAH",
    sale_price: "399 UAH",
    google_product_category: "4171",
    item_group_id: "457_27",
    product_type: "Постільна білизна",
    brand: "CottonHome",
    condition: "new",
  },

  {
    id: "55042",
    title: `Комплект постільної білизни "Париж"`,
    description: `Варіант "Париж" — класичний принт.`,
    link: "https://cottonhome.site/komplekt-postilnoi-bilyzny-paryzh/859/",
    image_link:
      "https://my.feededify.app/feedmaker/e3ab1a03-c9cc-4a80-80c4-f15f8c42092a/55042.jpg?v=6C0003F275539F466D258D9C141F33D5",
    availability: "in stock",
    price: "998 UAH",
    sale_price: "499 UAH",
    google_product_category: "4171",
    item_group_id: "457_27",
    product_type: "Постільна білизна",
    brand: "CottonHome",
    condition: "new",
  },

  {
    id: "55043",
    title: `Комплект постільної білизни "Париж"`,
    description: `Ще один SKU "Париж".`,
    link: "https://cottonhome.site/komplekt-postilnoi-bilyzny-paryzh./",
    image_link:
      "https://my.feededify.app/feedmaker/e3ab1a03-c9cc-4a80-80c4-f15f8c42092a/55043.jpg?v=FCA64B59C21F9070DC39DD43034C26E9",
    availability: "in stock",
    price: "1198 UAH",
    sale_price: "599 UAH",
    google_product_category: "4171",
    item_group_id: "457_27",
    product_type: "Постільна білизна",
    brand: "CottonHome",
    condition: "new",
  },

  {
    id: "55044",
    title: `Комплект постільної білизни "Париж"`,
    description: `Варіація "Париж" — білизна в класичному стилі.`,
    link: "https://cottonhome.site/komplekt-postilnoi-bilyzny-paryzh/",
    image_link:
      "https://my.feededify.app/feedmaker/e3ab1a03-c9cc-4a80-80c4-f15f8c42092a/55044.jpg?v=DE280AAC1B6010097FB0044E05BC2C8D",
    availability: "in stock",
    price: "1399 UAH",
    sale_price: "699 UAH",
    google_product_category: "4171",
    item_group_id: "457_27",
    product_type: "Постільна білизна",
    brand: "CottonHome",
    condition: "new",
  },

  {
    id: "55021",
    title: `Комплект постільної білизни "Мармур"`,
    description: `Мармур — бязь GOLD, елегантний принт, 115 г/м².`,
    link: "https://cottonhome.site/komplekt-postilnoi-bilyzny-marmur/",
    image_link:
      "https://my.feededify.app/feedmaker/e3ab1a03-c9cc-4a80-80c4-f15f8c42092a/55021.jpg?v=94CFA7B04752506C45F06B0522497931",
    additional_image_link:
      "https://cottonhome.site/content/images/30/komplekt-postilnoi-bilyzny-marmur-80513058973380_+4d122e3566.png",
    availability: "in stock",
    price: "798 UAH",
    sale_price: "398 UAH",
    google_product_category: "4171",
    item_group_id: "457_28",
    product_type: "Постільна білизна",
    brand: "CottonHome",
    condition: "new",
  },

  {
    id: "55022",
    title: `Комплект постільної білизни "Мармур"`,
    description: `Інший варіант "Мармур" — бязь GOLD.`,
    link: "https://cottonhome.site/komplekt-postilnoi-bilyzny-marmur/880/",
    image_link:
      "https://cottonhome.site/content/images/31/komplekt-postilnoi-bilyzny-marmurid-92173542675634_+5683eec754.jpg",
    additional_image_link:
      "https://cottonhome.site/content/images/31/komplekt-postilnoi-bilyzny-marmur880-26729640090490_+714d1a4bdb.png",
    availability: "out of stock",
    price: "998 UAH",
    sale_price: "499 UAH",
    google_product_category: "4171",
    item_group_id: "457_28",
    product_type: "Постільна білизна",
    brand: "CottonHome",
    condition: "new",
  },

  {
    id: "55023",
    title: `Комплект постільної білизни "Мармур"`,
    description: `Ще один SKU "Мармур".`,
    link: "https://cottonhome.site/komplekt-postilnoi-bilyzny-marmur/i/",
    image_link:
      "https://my.feededify.app/feedmaker/e3ab1a03-c9cc-4a80-80c4-f15f8c42092a/55023.jpg?v=82B27272452187F1788F39B59A1D80F6",
    additional_image_link:
      "https://cottonhome.site/content/images/32/komplekt-postilnoi-bilyzny-marmuri-91180610274044_+fc91b9b6bf.png",
    availability: "in stock",
    price: "1198 UAH",
    sale_price: "599 UAH",
    google_product_category: "4171",
    item_group_id: "457_28",
    product_type: "Постільна білизна",
    brand: "CottonHome",
    condition: "new",
  },

  {
    id: "55024",
    title: `Комплект постільної білизни "Мармур"`,
    description: `Варіант "Мармур" — елегантний дизайн.`,
    link: "https://cottonhome.site/komplekt-postilnoi-bilyzny-marmur/id/",
    image_link:
      "https://cottonhome.site/content/images/33/komplekt-postilnoi-bilyzny-marmurid-68340510953554_+07741d2539.jpg",
    additional_image_link:
      "https://cottonhome.site/content/images/33/komplekt-postilnoi-bilyzny-marmurid-68705126141149_+7a277c63b1.png",
    availability: "out of stock",
    price: "1399 UAH",
    sale_price: "699 UAH",
    google_product_category: "4171",
    item_group_id: "457_28",
    product_type: "Постільна білизна",
    brand: "CottonHome",
    condition: "new",
  },

  {
    id: "55057",
    title: `Комплект постільної білизни "Релакс"`,
    description: `Релакс — стримана елегантність, бязь GOLD, чорний.`,
    link: "https://cottonhome.site/komplekt-postilnoi-bilyzny-relaks/",
    image_link:
      "https://my.feededify.app/feedmaker/e3ab1a03-c9cc-4a80-80c4-f15f8c42092a/55057.jpg?v=2913EF8CDD4EEBABAA077EB6A61EBCD0",
    availability: "in stock",
    price: "798 UAH",
    sale_price: "399 UAH",
    google_product_category: "4171",
    item_group_id: "457_31",
    product_type: "Постільна білизна",
    brand: "CottonHome",
    condition: "new",
  },

  {
    id: "55058",
    title: `Комплект постільної білизни "Релакс"`,
    description: `Інша версія "Релакс".`,
    link: "https://cottonhome.site/komplekt-postilnoi-bilyzny-relaks/892/",
    image_link:
      "https://my.feededify.app/feedmaker/e3ab1a03-c9cc-4a80-80c4-f15f8c42092a/55058.jpg?v=3A0E6EF0324CAFC537B79A632B9146B7",
    availability: "in stock",
    price: "998 UAH",
    sale_price: "499 UAH",
    google_product_category: "4171",
    item_group_id: "457_31",
    product_type: "Постільна білизна",
    brand: "CottonHome",
    condition: "new",
  },

  {
    id: "55059",
    title: `Комплект постільної білизни "Релакс"`,
    description: `Ще один варіант "Релакс".`,
    link: "https://cottonhome.site/komplekt-postilnoi-bilyzny-relaks/id/",
    image_link:
      "https://my.feededify.app/feedmaker/e3ab1a03-c9cc-4a80-80c4-f15f8c42092a/55059.jpg?v=5AA8AA514312AD3D24A6D4C39D760526",
    availability: "in stock",
    price: "1198 UAH",
    sale_price: "599 UAH",
    google_product_category: "4171",
    item_group_id: "457_31",
    product_type: "Постільна білизна",
    brand: "CottonHome",
    condition: "new",
  },

  {
    id: "55060",
    title: `Комплект постільної білизни "Релакс"`,
    description: `Варіація "Релакс" — чорний комплект.`,
    link: "https://cottonhome.site/komplekt-postilnoi-bilyznrelaks/894/",
    image_link:
      "https://my.feededify.app/feedmaker/e3ab1a03-c9cc-4a80-80c4-f15f8c42092a/55060.jpg?v=B7B8E0BEDE3A40872F6B44A6C0386E0D",
    availability: "in stock",
    price: "1399 UAH",
    sale_price: "699 UAH",
    google_product_category: "4171",
    item_group_id: "457_31",
    product_type: "Постільна білизна",
    brand: "CottonHome",
    condition: "new",
  },

  {
    id: "55065",
    title: `Комплект постільної білизни "Білий"`,
    description: `"Білий" — мінімалістичний комплект, бязь GOLD.`,
    link: "https://cottonhome.site/komplekt-postilnoi-bilyzny-bilyi/",
    image_link:
      "https://my.feededify.app/feedmaker/e3ab1a03-c9cc-4a80-80c4-f15f8c42092a/55065.jpg?v=A6F75FD0B651B7E93901DA0E552C896D",
    availability: "in stock",
    price: "798 UAH",
    sale_price: "399 UAH",
    google_product_category: "4171",
    item_group_id: "457_33",
    product_type: "Постільна білизна",
    brand: "CottonHome",
    condition: "new",
  },

  {
    id: "55066",
    title: `Комплект постільної білизни "Білий"`,
    description: `Інша версія "Білий".`,
    link: "https://cottonhome.site/komplekt-postilnoi-bilyzny-bilyi/900/",
    image_link:
      "https://my.feededify.app/feedmaker/e3ab1a03-c9cc-4a80-80c4-f15f8c42092a/55066.jpg?v=15BBE6702F0E7191B9129DBF663CA33F",
    availability: "in stock",
    price: "998 UAH",
    sale_price: "499 UAH",
    google_product_category: "4171",
    item_group_id: "457_33",
    product_type: "Постільна білизна",
    brand: "CottonHome",
    condition: "new",
  },

  {
    id: "55067",
    title: `Комплект постільної білизни "Білий"`,
    description: `Ще один SKU "Білий".`,
    link: "https://cottonhome.site/komplekt-postilnoi-bilyzny-bilyi/901/",
    image_link:
      "https://my.feededify.app/feedmaker/e3ab1a03-c9cc-4a80-80c4-f15f8c42092a/55067.jpg?v=1310771CD9058DE1A1AED36F5A97949C",
    availability: "in stock",
    price: "1198 UAH",
    sale_price: "599 UAH",
    google_product_category: "4171",
    item_group_id: "457_33",
    product_type: "Постільна білизна",
    brand: "CottonHome",
    condition: "new",
  },

  {
    id: "55068",
    title: `Комплект постільної білизни "Білий"`,
    description: `Варіант "Білий" — класичний білий комплект.`,
    link: "https://cottonhome.site/komplekt-postilnoi-bilyzny-bilyi/902/",
    image_link:
      "https://my.feededify.app/feedmaker/e3ab1a03-c9cc-4a80-80c4-f15f8c42092a/55068.jpg?v=4EDB7AB5EBAC79716135BAC24A1B76B8",
    availability: "in stock",
    price: "1399 UAH",
    sale_price: "699 UAH",
    google_product_category: "4171",
    item_group_id: "457_33",
    product_type: "Постільна білизна",
    brand: "CottonHome",
    condition: "new",
  },

  {
    id: "55077",
    title: `Комплект постільної білизни "Цвіт сакури"`,
    description: `"Цвіт сакури" — ніжні кольори, високий комфорт.`,
    link: "https://cottonhome.site/komplekt-postilnoi-bilyzny-tsvit-sakura/933/",
    image_link:
      "https://my.feededify.app/feedmaker/e3ab1a03-c9cc-4a80-80c4-f15f8c42092a/55077.jpg?v=638FB5A8FB4CDDD9817DA1A444D9EE86",
    availability: "in stock",
    price: "798 UAH",
    sale_price: "399 UAH",
    google_product_category: "4171",
    item_group_id: "457_36",
    product_type: "Постільна білизна",
    brand: "CottonHome",
    condition: "new",
  },

  {
    id: "55078",
    title: `Комплект постільної білизни "Цвіт сакури"`,
    description: `Інший SKU "Цвіт сакури".`,
    link: "https://cottonhome.site/komplekt-postilnoi-bilyzny-tvit-sakura/934/",
    image_link:
      "https://my.feededify.app/feedmaker/e3ab1a03-c9cc-4a80-80c4-f15f8c42092a/55078.jpg?v=9B9B339C872E50BF46926E6B6EF481F0",
    availability: "in stock",
    price: "998 UAH",
    sale_price: "499 UAH",
    google_product_category: "4171",
    item_group_id: "457_36",
    product_type: "Постільна білизна",
    brand: "CottonHome",
    condition: "new",
  },

  {
    id: "55079",
    title: `Комплект постільної білизни "Цвіт сакури"`,
    description: `Ще варіант "Цвіт сакури".`,
    link: "https://cottonhome.site/komplekt-postilnoi-bilyzny-tsit-sakura/935/",
    image_link:
      "https://my.feededify.app/feedmaker/e3ab1a03-c9cc-4a80-80c4-f15f8c42092a/55079.jpg?v=D5409D82F16A44982C9A86874289A05D",
    availability: "in stock",
    price: "1198 UAH",
    sale_price: "599 UAH",
    google_product_category: "4171",
    item_group_id: "457_36",
    product_type: "Постільна білизна",
    brand: "CottonHome",
    condition: "new",
  },

  {
    id: "55080",
    title: `Комплект постільної білизни "Цвіт сакури"`,
    description: `Варіація "Цвіт сакури" — елегантний комплект.`,
    link: "https://cottonhome.site/komplekt-postilnoi-bilyzny-tsvit-sakura/",
    image_link:
      "https://my.feededify.app/feedmaker/e3ab1a03-c9cc-4a80-80c4-f15f8c42092a/55080.jpg?v=C7941047FEC83ABDCDDC8983FB43BEF2",
    availability: "in stock",
    price: "1399 UAH",
    sale_price: "699 UAH",
    google_product_category: "4171",
    item_group_id: "457_36",
    product_type: "Постільна білизна",
    brand: "CottonHome",
    condition: "new",
  },

  {
    id: "55081",
    title: `Комплект постільної білизни "Мармур чорний"`,
    description: `Мармур чорний — принт під чорний мармур, бязь GOLD.`,
    link: "https://cottonhome.site/komplekt-postilnoi-bilyzny-marmur-chornyi/937/",
    image_link:
      "https://my.feededify.app/feedmaker/e3ab1a03-c9cc-4a80-80c4-f15f8c42092a/55081.jpg?v=7267719451399D5E0D2D25867EFA3FBD",
    availability: "in stock",
    price: "778 UAH",
    sale_price: "399 UAH",
    google_product_category: "4171",
    item_group_id: "457_37",
    product_type: "Постільна білизна",
    brand: "CottonHome",
    condition: "new",
  },

  {
    id: "55082",
    title: `Комплект постільної білизни "Мармур чорний"`,
    description: `Інша версія "Мармур чорний".`,
    link: "https://cottonhome.site/komplekt-pstilnoi-bilyzny-marmur-chornyi/938/",
    image_link:
      "https://my.feededify.app/feedmaker/e3ab1a03-c9cc-4a80-80c4-f15f8c42092a/55082.jpg?v=1D3E06C4BCD90C43C93CFFD7DBE9B463",
    availability: "in stock",
    price: "998 UAH",
    sale_price: "499 UAH",
    google_product_category: "4171",
    item_group_id: "457_37",
    product_type: "Постільна білизна",
    brand: "CottonHome",
    condition: "new",
  },

  {
    id: "55083",
    title: `Комплект постільної білизни "Мармур чорний"`,
    description: `Ще один SKU "Мармур чорний".`,
    link: "https://cottonhome.site/komplekt-postilnoi-bilyzny-marur-chornyi/939/",
    image_link:
      "https://my.feededify.app/feedmaker/e3ab1a03-c9cc-4a80-80c4-f15f8c42092a/55083.jpg?v=C17DEFDCF79B3D3C6DA309F806802AC8",
    availability: "in stock",
    price: "1198 UAH",
    sale_price: "599 UAH",
    google_product_category: "4171",
    item_group_id: "457_37",
    product_type: "Постільна білизна",
    brand: "CottonHome",
    condition: "new",
  },

  {
    id: "55084",
    title: `Комплект постільної білизни "Мармур чорний"`,
    description: `Варіант "Мармур чорний" — елегантний принт.`,
    link: "https://cottonhome.site/komplekt-postilnoi-bilyzny-marmur-chornyi/",
    image_link:
      "https://my.feededify.app/feedmaker/e3ab1a03-c9cc-4a80-80c4-f15f8c42092a/55084.jpg?v=9E246DCBE43A9784D27A6942ABDB94AA",
    availability: "in stock",
    price: "1399 UAH",
    sale_price: "699 UAH",
    google_product_category: "4171",
    item_group_id: "457_37",
    product_type: "Постільна білизна",
    brand: "CottonHome",
    condition: "new",
  },

  {
    id: "55085",
    title: `Комплект постільної білизни "Ромашкові сни"`,
    description: `Ромашкові сни — ніжна колекція, високий комфорт.`,
    link: "https://cottonhome.site/komplekt-postilnoi-bilyzny-romashkovi-sny/941/",
    image_link:
      "https://my.feededify.app/feedmaker/e3ab1a03-c9cc-4a80-80c4-f15f8c42092a/55085.jpg?v=7754C9CCF33CD07D7592C27B21EB1E3C",
    availability: "in stock",
    price: "798 UAH",
    sale_price: "399 UAH",
    google_product_category: "4171",
    item_group_id: "457_38",
    product_type: "Постільна білизна",
    brand: "CottonHome",
    condition: "new",
  },

  {
    id: "55086",
    title: `Комплект постільної білизни "Ромашкові сни"`,
    description: `Інший SKU "Ромашкові сни".`,
    link: "https://cottonhome.site/komplekt-postilnoi-bilyzny-romashkovi-sny/942/",
    image_link:
      "https://cottonhome.site/content/images/43/komplekt-postilnoi-bilyzny-romashkovi-snyid-89972002017176_+a880122407.jpg",
    availability: "out of stock",
    price: "998 UAH",
    sale_price: "499 UAH",
    google_product_category: "4171",
    item_group_id: "457_38",
    product_type: "Постільна білизна",
    brand: "CottonHome",
    condition: "new",
  },

  {
    id: "55087",
    title: `Комплект постільної білизни "Ромашкові сни"`,
    description: `Ще один варіант "Ромашкові сни".`,
    link: "https://cottonhome.site/komplekt-postilnoi-bilzny-romashkovi-sny/943/",
    image_link:
      "https://cottonhome.site/content/images/44/komplekt-postilnoi-bilzny-romashkovi-snyid-52420304641099_+43e5c5fad8.jpg",
    availability: "out of stock",
    price: "1198 UAH",
    sale_price: "599 UAH",
    google_product_category: "4171",
    item_group_id: "457_38",
    product_type: "Постільна білизна",
    brand: "CottonHome",
    condition: "new",
  },

  {
    id: "55088",
    title: `Комплект постільної білизни "Ромашкові сни"`,
    description: `Варіація "Ромашкові сни" — ще SKU.`,
    link: "https://cottonhome.site/komplekt-postilnoi-bilyzny-romashkovi-sny/",
    image_link:
      "https://my.feededify.app/feedmaker/e3ab1a03-c9cc-4a80-80c4-f15f8c42092a/55088.jpg?v=69163F25DC53ADD2E313CBABEA521072",
    availability: "in stock",
    price: "1399 UAH",
    sale_price: "699 UAH",
    google_product_category: "4171",
    item_group_id: "457_38",
    product_type: "Постільна білизна",
    brand: "CottonHome",
    condition: "new",
  },

  {
    id: "55089",
    title: `Комплект постільної білизни "Контур"`,
    description: `Контур — бежевий комплект з бязі GOLD, комфортний і надійний.`,
    link: "https://cottonhome.site/komplekt-postilnoi-bilyzny-kontur/",
    image_link:
      "https://cottonhome.site/content/images/46/komplekt-postilnoi-bilyzny-kontur-13487742558708_+bd79b5fa74.jpg",
    availability: "out of stock",
    price: "798 UAH",
    sale_price: "399 UAH",
    google_product_category: "4171",
    item_group_id: "457_39",
    product_type: "Постільна білизна",
    brand: "CottonHome",
    condition: "new",
  },

  {
    id: "55090",
    title: `Комплект постільної білизни "Контур"`,
    description: `Інша версія "Контур".`,
    link: "https://cottonhome.site/komplekt-postiloi-bilyzny-kontur/946/",
    image_link:
      "https://cottonhome.site/content/images/47/komplekt-postiloi-bilyzny-konturid-78156717304910_+48ad7be9b6.jpg",
    availability: "out of stock",
    price: "998 UAH",
    sale_price: "499 UAH",
    google_product_category: "4171",
    item_group_id: "457_39",
    product_type: "Постільна білизна",
    brand: "CottonHome",
    condition: "new",
  },

  {
    id: "55091",
    title: `Комплект постільної білизни "Контур"`,
    description: `Ще один SKU "Контур".`,
    link: "https://cottonhome.site/komplekt-postilnoi-bilyzny-kontur/947/",
    image_link:
      "https://cottonhome.site/content/images/48/komplekt-postilni-bilyzny-konturid-87839073678896_+13b2a3e1cd.jpg",
    availability: "out of stock",
    price: "1198 UAH",
    sale_price: "599 UAH",
    google_product_category: "4171",
    item_group_id: "457_39",
    product_type: "Постільна білизна",
    brand: "CottonHome",
    condition: "new",
  },

  {
    id: "55092",
    title: `Комплект постільної білизни "Контур"`,
    description: `Варіація "Контур" — класичний бежевий комплект.`,
    link: "https://cottonhome.site/komplekt-postilnoi-bilyzny-kontur/948/",
    image_link:
      "https://my.feededify.app/feedmaker/e3ab1a03-c9cc-4a80-80c4-f15f8c42092a/55092.jpg?v=35FF2A0942A8E7CE2A41270D9F90F589",
    availability: "in stock",
    price: "1399 UAH",
    sale_price: "699 UAH",
    google_product_category: "4171",
    item_group_id: "457_39",
    product_type: "Постільна білизна",
    brand: "CottonHome",
    condition: "new",
  },
];
